### ISSUE TITLE
Refactor overall UI design 🎯 2 days

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#72]
Things to consider during the design phase:

* Improve readability of time display

  The time display (and most of the presentational UI bits) should be useable on a 24" "confidence monitor" setup about 5ft. from the foot of a stage. That means things should be rather large and uncomplicated to increase readability. Also consider accessibility concerns like color contrast.

  "Configuration" bits of the UI can remain at a more reasonable size for usage by off-stage staff sitting directly in front of the computer

* The screen seen by the off-stage staff is mirrored to the "confidence monitors" setup in front of the stage.

* Add conditional rendering of stopwatch and timer (only one is displayed at a time)
  * Tabs?
  * Toggle button?
  * Something else?
* Improve visual design ("make it nicer to look at")

**Comment by meingorn** [comment]
broke this down into a few issues

**Comment by kaxcode** [comment]
Closed with the implementation in the following tickets : #110, #116, #117, #118, #119.
