### ISSUE TITLE
Fix "key" error in test suite 🎯1/2 day

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#73]
Whenever the test suite is run, React throws and error/warning that a `key` is required when rendering an array of components. This is errant in that the tests are _not_ rendering an array of anything.

The source of this bug appears to be traced back to the usage of shallow rendering a component, calling `toJSON` on the result, and then passing that to `toMatchSnapshot()`.

The docs seem to indicate that the `toJSON` step is unnecessary and `toMatchSnapshot()` can handle the output of Enzyme's shallow rendering as is.

In a previous attempt at fixing this, removing `toJSON` did significantly increase the size of the snapshot file by almost 10x. Whatever the resolution of this fix is, the size of the snapshots should be considered along with the state that is saved to the snapshot.

Additionally, we may want to look at what exactly we are gaining by including `enzyme` in the test suite. If it is not offering any additional functionality of `react-test-utils`, then we should consider removing `enzyme` and relying solely on what `jest` and `react-test-utils` provides out of the box.

**Comment by kaxcode** [comment]
The solution was not to remove `toJson` but do render out the component (ex. <Timer />) instead of a shallow render.
