### ISSUE TITLE
Add ability for off-stage staff to communicate message to on-stage talent - 2 days

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#75]
During the course of a presentation on stage, the off-stage staff may need to relay an important message to the person on-stage. Possible scenarios:

* Remind the presenter to mention to the audience where the bathrooms are located
* Encourage the presenter to stall because of some unforeseen delay in the next segment of the program
* An emergency situation where the presenter must calmly instruct the attendees to vacate the premisis

While it appears that there could be some varying levels of urgency in these messages, it is no requirement to provide a mechanism to visually disambiguate the severity of these messages. Consider them to all be of equal importance.

It is possible that throughout the course of a presentation, multiple messages could be relayed by the off-stage staff and acted upon by the on-stage talent. Old message should be removed or otherwise deemphasized from the UI.

There should be some mechanism for the off-stage talent to type into an input in order for that message to be relayed. The presentation of the message could be the input itself, a completely different component, or something else entirely (use any of these or your own imagination)

**Comment by kaxcode** [comment]
Blocked by #72, waiting on implementation of redesign.
