### ISSUE TITLE
Refactor CSS classnames to implement BEM - 1 day

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#76]
In order to improve the maintainability of the CSS, we should implement the [BEM standard of naming conventions](http://getbem.com/naming/).

Staying away from the "cascade" portion of CSS makes it easier to override certain CSS properties by avoiding the complexity of rule specificity.

Because we are working in a React codebase and all components are in upper CamelCase, all "block" and "element" names should mirror the capitalization of the block component.

```jsx
const MyComponent = () => (
  <div className="MyComponent">
    <button className="MyComponent__Button--enabled"/>
  </div>
)
```

**Comment by dlindahl** [comment]
I forgot to mention this during our last retrospective.

**Comment by meingorn** [comment]
pushing to next sprint

**Comment by meingorn** [comment]
probably best if we save this for the impending css rewrite that is coming with the redesign - may merge w/ other css issues
