### ISSUE TITLE
Improve output of milliseconds in timer display

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#94]
Currently, the stopwatch renders a time of `00:00:00:10` where `10` is the current elapsed milliseconds. I believe the standard for rendering milliseconds is to use `.` as a delimiter.

Research this and if it makes sense, make the change.

**Comment by meingorn** [comment]
After doing some research haven't found any evidence of this. The standard appears to be either the formatting as we currently have it or with letters ('s/ minutes/ hrs' etc) rather than punctuation. Leaving this open until we discuss

**Comment by dlindahl** [comment]
After a bit of research myself, decimal fractions of a second is part of the ISO8601 standard. Unfortunately, that is locked behind a paywall.

But here are some free resources that also cover it:

* https://www.w3.org/TR/NOTE-datetime
* http://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm
* https://www.cl.cam.ac.uk/~mgk25/iso-time.html
* https://nbsoftsolutions.com/blog/iso-8601-and-nanosecond-precision-across-languages

And some other code/real-world examples:

* https://gist.github.com/dstagner/193207fed46acf5b5bae
* https://beginnersbook.com/2017/10/java-time-in-milliseconds-format/
* http://www.estopwatch.net/
* https://www.youtube.com/watch?v=9cQT4urTlXM
* https://www.extendoffice.com/documents/excel/3242-excel-show-milliseconds.html
* https://stackoverflow.com/questions/16032451/get-datetime-now-with-milliseconds-precision
* https://superuser.com/questions/674464/print-current-time-with-milliseconds
* https://youtu.be/usdHlrUra4A?t=4m59s
* https://community.powerbi.com/t5/Desktop/Time-Duration-including-milliseconds/td-p/66670

**Comment by kaxcode** [comment]
Changes will be implemented in #117
