### ISSUE TITLE
Add `defaultProps` to `Stopwatch` component

### ISSUE THREAD

**Issue by dlindahl** [kaxcode/cloudwatch#95]
While [`props.counter || 0`](https://github.com/kaxcode/cloudwatch/blob/f4544f9af4da79da2fd26800290058ef9018ece5/src/components/Stopwatch/Stopwatch.js#L12) is not necessarily wrong, the declarative nature of React prefers to use [`defaultProps`](https://reactjs.org/docs/typechecking-with-proptypes.html#default-prop-values) to set default prop values.

Move this default value handler to be a default prop.

**Comment by kaxcode** [comment]
Closed in PR #98
